// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanNuocMVC.Data;

#nullable disable

namespace WebBanNuocMVC.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanNuocMVC.Data.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA586E16F74FB");

                    b.HasIndex(new[] { "Username" }, "UQ__Account__536C85E400545F73")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.CafeTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TableID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TableId")
                        .HasName("PK__CafeTabl__7D5F018E0C35872C");

                    b.ToTable("CafeTable", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A2BD256CCFD");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B835CE1DC1");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinkId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DrinkName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DrinkId")
                        .HasName("PK__Drink__C094D3C8E00D0167");

                    b.HasIndex("CategoryId");

                    b.ToTable("Drink", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("TableID");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BAFDAE24507");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("DrinkId")
                        .HasColumnType("int")
                        .HasColumnName("DrinkID");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C858E3E6C");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.RevenueReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateOnly?>("ReportDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ReportId")
                        .HasName("PK__RevenueR__D5BD48E5C9DA98E8");

                    b.ToTable("RevenueReport", (string)null);
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Drink", b =>
                {
                    b.HasOne("WebBanNuocMVC.Data.Category", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Drink__CategoryI__3C69FB99");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Order", b =>
                {
                    b.HasOne("WebBanNuocMVC.Data.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Order__AccountID__44FF419A");

                    b.HasOne("WebBanNuocMVC.Data.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Order__CustomerI__440B1D61");

                    b.HasOne("WebBanNuocMVC.Data.CafeTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .HasConstraintName("FK__Order__TableID__4316F928");

                    b.Navigation("Account");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.OrderDetail", b =>
                {
                    b.HasOne("WebBanNuocMVC.Data.Drink", "Drink")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DrinkId")
                        .HasConstraintName("FK__OrderDeta__Drink__48CFD27E");

                    b.HasOne("WebBanNuocMVC.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__47DBAE45");

                    b.Navigation("Drink");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Account", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.CafeTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Category", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Drink", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebBanNuocMVC.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
